name: project_xxx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipykernel=5.5.0
  - pandas==1.2.0
  - pandas-gbq=0.14.1
  - tqdm=4.57.0
  - pip=21.0.1
  - pip:
      - -e /full/path/to/package/data_analytics/
variables:
  USER_NAME: user_name
  TEAM: team_name